// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6ybtqz-OnU9cAN-uDlv08kC_SQuKS0MY',
    appId: '1:861014531257:web:e63b9a0dfcabca816c0f68',
    messagingSenderId: '861014531257',
    projectId: 'health-nexus-5d24e',
    authDomain: 'health-nexus-5d24e.firebaseapp.com',
    storageBucket: 'health-nexus-5d24e.firebasestorage.app',
    measurementId: 'G-VD344B22VT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH5LivR_HRPNLHRQP7cwxyWyCoeifWTzE',
    appId: '1:861014531257:android:8019a540194854d96c0f68',
    messagingSenderId: '861014531257',
    projectId: 'health-nexus-5d24e',
    storageBucket: 'health-nexus-5d24e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNGfC7eYK0F_sjn5cYWtk0tFg1RCU87VU',
    appId: '1:861014531257:ios:e82bb6dc4a837c7c6c0f68',
    messagingSenderId: '861014531257',
    projectId: 'health-nexus-5d24e',
    storageBucket: 'health-nexus-5d24e.firebasestorage.app',
    iosBundleId: 'com.example.drAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNGfC7eYK0F_sjn5cYWtk0tFg1RCU87VU',
    appId: '1:861014531257:ios:e82bb6dc4a837c7c6c0f68',
    messagingSenderId: '861014531257',
    projectId: 'health-nexus-5d24e',
    storageBucket: 'health-nexus-5d24e.firebasestorage.app',
    iosBundleId: 'com.example.drAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6ybtqz-OnU9cAN-uDlv08kC_SQuKS0MY',
    appId: '1:861014531257:web:258d5143ad23e1896c0f68',
    messagingSenderId: '861014531257',
    projectId: 'health-nexus-5d24e',
    authDomain: 'health-nexus-5d24e.firebaseapp.com',
    storageBucket: 'health-nexus-5d24e.firebasestorage.app',
    measurementId: 'G-ZD2RB66RFH',
  );

}